-- 피드백 테이블 생성
CREATE TABLE feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL, -- 'compliment'(칭찬), 'suggestion'(제안), 'bug'(불편)
  content TEXT NOT NULL,
  email TEXT, -- 답변받을 이메일 (선택사항)
  status TEXT DEFAULT 'pending', -- 'pending'(대기), 'completed'(완료)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS 정책 설정 (누구나 쓸 수 있게)
ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for everyone" ON feedbacks
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read for service role only" ON feedbacks
    FOR SELECT USING (false); -- 일반 사용자는 조회 불가
